# DSC 80 Practice Exam

In [1]:
from dsc80_utils import *
pd.set_option('display.max_rows', None)

songs = pd.DataFrame({
    "title": ["Blinding Lights", "Shape of You", "Bohemian Rhapsody", "Stairway to Heaven", "Take Five"],
    "artist": ["The Weeknd", "Ed Sheeran", "Queen", "Led Zeppelin", "Dave Brubeck"],
    "genre": ["Pop", "Pop", "Rock", "Rock", "Jazz"],
    "streams": [3000000, 2500000, 1500000, 900000, 400000]
})


A = pd.DataFrame({
    "sid": [1, 2, 2, 3, 5],
    "name": ["Alice", "Bob", "Bob", np.nan, "Eve"],
    "age": [20, np.nan, 21, 22, 23]
})

B = pd.DataFrame({
    "sid": [1, 1, 2, 2, 4],
    "course": ["Math", "Bio", np.nan, "Chem", "CS"]
})


sessions = pd.DataFrame({
    "tutor": ["Annabelle", "Ishayu", "Ishayu", "Ishayu", 
              "Annabelle", "Annabelle", "Annabelle",
              "Ishayu", "Ishayu", "Ishayu", "Ishayu", "Ishayu", "Ishayu"],
    "subject": ["Math", "Math", "Math", "Math", 
                "English", "English", "English",
                "English", "English", "English", "English", "English", "English"],
    "length": ["Long", "Short", "Short", "Long", 
               "Long", "Long", "Long",
               "Short", "Long", "Long", "Long", "Long", "Long"],
    "score_gain": [5.0, 9.5, 9.5, 5.0, 
                   9.0, 9.0, 9.0, 
                   6.0, 9.0, 9.0, 9.0, 9.0, 9.0]
})

calls = pd.DataFrame({
    "day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun", "Mon"],
    "hour": [9, 14, 10, 16, 11, 20, 8, 15],
    "wait_time": [5.0, 12.0, np.nan, 15.0, 4.0, 20.0, np.nan, 10.0]
})

## Problem 1

In [2]:
songs

                title        artist genre  streams
0     Blinding Lights    The Weeknd   Pop  3000000
1        Shape of You    Ed Sheeran   Pop  2500000
2   Bohemian Rhapsody         Queen  Rock  1500000
3  Stairway to Heaven  Led Zeppelin  Rock   900000
4           Take Five  Dave Brubeck  Jazz   400000

In [3]:
# 1a, code doesn't work
songs.groupby("genre").max()["title"]

genre
Jazz             Take Five
Pop           Shape of You
Rock    Stairway to Heaven
Name: title, dtype: object

In [4]:
# 1b solution
songs.sort_values("streams", ascending=False).groupby("genre")["title"].first()

genre
Jazz            Take Five
Pop       Blinding Lights
Rock    Bohemian Rhapsody
Name: title, dtype: object

In [5]:
# 1b alternate solution
songs.set_index("title").groupby("genre")["streams"].idxmax()

genre
Jazz            Take Five
Pop       Blinding Lights
Rock    Bohemian Rhapsody
Name: streams, dtype: object

In [6]:
# 1c solution
(
    songs[songs["streams"] >= 1000000]
    .set_index("title")
    .groupby("genre")["streams"]
    .transform(lambda s: s.mean())
)

title
Blinding Lights      2.75e+06
Shape of You         2.75e+06
Bohemian Rhapsody    1.50e+06
Name: streams, dtype: float64

## Problem 2

In [7]:
A

   sid   name   age
0    1  Alice  20.0
1    2    Bob   NaN
2    2    Bob  21.0
3    3    NaN  22.0
4    5    Eve  23.0

In [8]:
B

   sid course
0    1   Math
1    1    Bio
2    2    NaN
3    2   Chem
4    4     CS

In [19]:
# outer merge
A.merge(B, on="sid", how="outer")

   sid   name   age course
0    1  Alice  20.0   Math
1    1  Alice  20.0    Bio
2    2    Bob   NaN    NaN
3    2    Bob   NaN   Chem
4    2    Bob  21.0    NaN
5    2    Bob  21.0   Chem
6    3    NaN  22.0    NaN
7    4    NaN   NaN     CS
8    5    Eve  23.0    NaN

In [10]:
# inner merge
A.merge(B, on="sid", how="inner")

   sid   name   age course
0    1  Alice  20.0   Math
1    1  Alice  20.0    Bio
2    2    Bob   NaN    NaN
3    2    Bob   NaN   Chem
4    2    Bob  21.0    NaN
5    2    Bob  21.0   Chem

## Problem 3

In [11]:
sessions

        tutor  subject length  score_gain
0   Annabelle     Math   Long         5.0
1      Ishayu     Math  Short         9.5
2      Ishayu     Math  Short         9.5
..        ...      ...    ...         ...
10     Ishayu  English   Long         9.0
11     Ishayu  English   Long         9.0
12     Ishayu  English   Long         9.0

[13 rows x 4 columns]

In [12]:
# 3a solution
sessions.pivot_table(index="tutor", columns="subject", values="score_gain", aggfunc="mean")

subject    English  Math
tutor
Annabelle      9.0   5.0
Ishayu         8.5   8.0